### ISSUE TITLE
how to start kupiki admin

### ISSUE THREAD

**Issue by macalimosa** [Kupiki/Kupiki-Hotspot-Admin-Frontend#3]
how to configure this to make this work? also how can i access the admin?

**Comment by pihomeserver** [comment]
2 ways :

1.  Set to Y the parameter INSTALL_KUPIKI_ADMIN in the installation script
1. If you don't want to reinstall all then you can use the repo https://github.com/Kupiki/Kupiki-Hotspot-Admin-Install

Keep in mind that it's in development so you can have bugs

**Comment by KirDE** [comment]
I installed admin using this installation script, but how can i access it? which URL or port should i use?

**Comment by pihomeserver** [comment]
IP of the Raspberry on the port 3000. user admin/password admin

The version is obsolete and will be released under Docker images
